name: Build and Release Executable

on:
  push:
    tags:
      - 'v*' # Executa quando um novo tag é criado (ex.: v1.0.0)

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller main.spec

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: app_windows_executable
          path: dist/app.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # Usa o nome do tag como versão
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/app.exe
          asset_name: app.exe
          asset_content_type: application/octet-stream
